Add debug tooling to deploy-doc-tests/run
microservices-demo/microservices-demo pull request #406
Opened 2016-11-14 12:57 UTC by moretea

Add `-d` and `-s` options to `deploy-doc-tests/run` command

If either of these options is invoked, no test is run.

- `-d`, or `--shell-in-container` starts an interactive docker container with the same 'environment' as where the tests are run.
- `-s`, or `--output-shell-script` does what it's name implies; write a
shell script containing all the steps (in the correct order) to the
standard output.

2016-11-15 01:43 UTC, vlal-zz reviewed
LGTM, just one comment

2016-11-15 01:43 UTC, vlal commented on deploy-doc-tests/lib/deploy_doc_test/plan.rb
> +          p step
does this print the step as well?

2016-11-15 13:46 UTC, frankscholten reviewed
How about renaming `run` to `deploydoc`?

2016-11-16 14:19 UTC, pidster requested changes
Please change 'run' to 'deploydoc' per Frank.

2016-11-18 11:14 UTC, moretea commented
I don't think `deploydoc` is the correct term. The invocation would be `deploy-doc-tests/deploy-doc`.
I still think that `deploy-doc-test/run` is better.

A compromise would be to rename it to `deploy-doc-test/run-deploy-doc-test`

2016-11-18 12:46 UTC, moretea commented
OK, had a chat with Frank. We consider extracting this as a separate project, having a `deploydoc` command makes sense in that case.

2016-11-18 14:43 UTC, pidster submitted a review, later dismissed

2016-11-18 14:45 UTC, pidster requested changes
There's a merge conflict in `deploy-doc-tests/Dockerfile`.

2016-11-18 15:16 UTC, moretea commented
Yes, don't know what happened here, I'm going to investigate the history of this branch a bit.

2016-11-18 15:46 UTC, pidster commented
@moretea @frankscholten Making the doc tool a separate project is good idea. If you can't create a repo in this org, shout & I'll sort it for you.

2016-11-24 14:35 UTC, moretea commented
Closing, will merge these changes into https://github.com/microservices-demo/deploydoc

2016-11-24 14:35 UTC, closed without merging