[WIP] Enhancement/opentracing
microservices-demo/microservices-demo pull request #499
Opened 2016-12-27 08:16 UTC by jasonrichardsmith

resolves #498 for catalogue and user only

2017-01-05 12:41 UTC, philwinder requested changes

2017-01-05 12:41 UTC, philwinder commented on deploy/docker-compose/docker-compose.yml
> +      - reschedule=on-node-failure
AFAIK, reschedule is only for docker swarm.

2017-01-05 12:41 UTC, philwinder commented on deploy/docker-compose-weave/docker-compose.yml
> +  zipkin:
Not attached to any network. Is that intentional?

2017-01-05 12:41 UTC, philwinder commented on deploy/kubernetes/manifests/catalogue-dep.yaml
>          image: weaveworksdemos/catalogue:0.2.0
Wrong catalogue version

2017-01-11 11:05 UTC, jasonrichardsmith commented
Closed, each deployment got its own PR.

2017-01-11 11:05 UTC, closed without merging