load tests instructions for minikube
microservices-demo/microservices-demo pull request #507
Opened 2017-01-03 15:02 UTC by nustiueudinastea

For consistency, added instructions on how to perform load tests for k8s minikube. Related to this request: https://github.com/microservices-demo/microservices-demo/issues/207

2017-01-03 19:00 UTC, vlal commented on docs/deployment/kubernetes-minikube.md
> +docker run --rm weaveworksdemos/load-test -d 5 http://192.168.99.100:30001 -c 3 -r 10
missing `-h` flag

2017-01-04 11:26 UTC, pidster requested changes
Please verify that the load-test command has been tested as it is described.

2017-01-04 11:26 UTC, pidster commented on docs/deployment/kubernetes-minikube.md
> +docker run --rm weaveworksdemos/load-test -d 5 -h http://192.168.99.100:30001 -c 3 -r 10
Have you tested this?

2017-01-06 11:01 UTC, nustiueudinastea commented
@pidster fixed the issue with the command.

2017-01-06 14:03 UTC, pidster approved these changes

2017-01-06 14:03 UTC, merged