various improvements to the loat_tests
microservices-demo/microservices-demo pull request #531
Opened 2017-01-10 11:53 UTC by nustiueudinastea

- added a section for the ECS load tests
- improved the command flags for locust.io, for all the load tests

2017-01-10 12:02 UTC, nustiueudinastea commented
Related to https://github.com/microservices-demo/microservices-demo/issues/207

2017-01-12 11:22 UTC, pidster requested changes
Please resolve the conflicts in the ECS file

2017-01-16 12:53 UTC, nustiueudinastea commented
@pidster updated and fixed

2017-01-16 15:24 UTC, pidster approved these changes

2017-01-16 15:24 UTC, merged